export const functionPackages = {
  silver: { price: 2800, name: 'Silver Package', features: ['Venue', 'Basic Decoration', 'Standard Catering'] },
  gold: { price: 3200, name: 'Gold Package', features: ['Premium Venue', 'Premium Decoration', 'Premium Catering', 'Music System'] },
  premium: { price: 3500, name: 'Premium Package', features: ['Luxury Venue', 'Designer Decoration', 'Gourmet Catering', 'Live Band', 'Photography'] }
};

export const roomServiceChargeRate = 0.10;
export const functionServiceChargeRate = 0.10;
export const restaurantServiceChargeRate = 0.10;
export const APP_NAME = 'Summit Resort';

// ─── RESTAURANT MENU ────────────────────────────────────────────────────────
// Each item: { id, name, price }   (price in LKR)
// Items with size variants are listed separately (e.g. "Chicken Noodles (S)")

export const restaurantMenu = {
  'Clear Soups': [
    { id: 'cs1', name: 'Egg Corn Soup', price: 550 },
    { id: 'cs2', name: 'Corn and Chicken Soup', price: 750 },
    { id: 'cs3', name: 'Mushroom Coriander Soup', price: 600 },
    { id: 'cs4', name: 'Chicken Coriander Soup', price: 700 },
    { id: 'cs5', name: 'Beef Soup', price: 850 },
    { id: 'cs6', name: 'Seafood Soup', price: 900 },
  ],
  'Cream Soups': [
    { id: 'crs1', name: 'Cream of Vegetable Soup', price: 600 },
    { id: 'crs2', name: 'Cream of Pumpkin Soup', price: 600 },
    { id: 'crs3', name: 'Cream of Chicken Soup', price: 800 },
    { id: 'crs4', name: 'Cream of Prawn & Cuttlefish Soup', price: 950 },
  ],
  'Fried Rice': [
    { id: 'fr1', name: 'Vegetable Fried Rice (R)', price: 500 },
    { id: 'fr2', name: 'Vegetable Fried Rice (L)', price: 800 },
    { id: 'fr3', name: 'Egg Fried Rice (R)', price: 600 },
    { id: 'fr4', name: 'Egg Fried Rice (L)', price: 900 },
    { id: 'fr5', name: 'Chicken Fried Rice (R)', price: 900 },
    { id: 'fr6', name: 'Chicken Fried Rice (L)', price: 1200 },
    { id: 'fr7', name: 'Mixed Fried Rice (R)', price: 1450 },
    { id: 'fr8', name: 'Mixed Fried Rice (L)', price: 1850 },
    { id: 'fr9', name: 'Seafood Fried Rice (R)', price: 1450 },
    { id: 'fr10', name: 'Seafood Fried Rice (L)', price: 1850 },
    { id: 'fr11', name: 'Special Mixed Fried Rice (R)', price: 1600 },
    { id: 'fr12', name: 'Special Mixed Fried Rice (L)', price: 2100 },
  ],
  'Biriyani': [
    { id: 'br1', name: 'Vegetable Biriyani (R)', price: 600 },
    { id: 'br2', name: 'Vegetable Biriyani (L)', price: 900 },
    { id: 'br3', name: 'Chicken Biriyani (R)', price: 1100 },
    { id: 'br4', name: 'Chicken Biriyani (L)', price: 1850 },
    { id: 'br5', name: 'Beef Biriyani (R)', price: 1550 },
    { id: 'br6', name: 'Beef Biriyani (L)', price: 2100 },
    { id: 'br7', name: 'Mutton Biriyani (R)', price: 1650 },
    { id: 'br8', name: 'Mutton Biriyani (L)', price: 2200 },
  ],
  'Chop Suey Rice': [
    { id: 'csr1', name: 'Vegetable Chop Suey Rice (S)', price: 1200 },
    { id: 'csr2', name: 'Vegetable Chop Suey Rice (L)', price: 1700 },
    { id: 'csr3', name: 'Chicken Chop Suey Rice (S)', price: 1450 },
    { id: 'csr4', name: 'Chicken Chop Suey Rice (L)', price: 1950 },
    { id: 'csr5', name: 'Seafood Chop Suey Rice (S)', price: 1800 },
    { id: 'csr6', name: 'Seafood Chop Suey Rice (L)', price: 2200 },
  ],
  'Nasi Goreng': [
    { id: 'ng1', name: 'Chicken Nasi Goreng (R)', price: 950 },
    { id: 'ng2', name: 'Chicken Nasi Goreng (L)', price: 1300 },
    { id: 'ng3', name: 'Seafood Nasi Goreng (R)', price: 1300 },
    { id: 'ng4', name: 'Seafood Nasi Goreng (L)', price: 1950 },
    { id: 'ng5', name: 'Beef Nasi Goreng (R)', price: 1550 },
    { id: 'ng6', name: 'Beef Nasi Goreng (L)', price: 2000 },
    { id: 'ng7', name: 'Mutton Nasi Goreng (R)', price: 1650 },
    { id: 'ng8', name: 'Mutton Nasi Goreng (L)', price: 2100 },
  ],
  'Tomato Rice': [
    { id: 'tr1', name: 'Chicken Tomato Rice (R)', price: 950 },
    { id: 'tr2', name: 'Chicken Tomato Rice (L)', price: 1300 },
    { id: 'tr3', name: 'Seafood Tomato Rice (R)', price: 1300 },
    { id: 'tr4', name: 'Seafood Tomato Rice (L)', price: 1850 },
    { id: 'tr5', name: 'Beef Tomato Rice (R)', price: 1550 },
    { id: 'tr6', name: 'Beef Tomato Rice (L)', price: 2000 },
  ],
  'Corn & Garlic Rice': [
    { id: 'cgr1', name: 'Chicken Corn Rice (R)', price: 1000 },
    { id: 'cgr2', name: 'Chicken Corn Rice (L)', price: 1300 },
    { id: 'cgr3', name: 'Prawns Corn Rice (R)', price: 1200 },
    { id: 'cgr4', name: 'Prawns Corn Rice (L)', price: 1850 },
    { id: 'cgr5', name: 'Chicken Garlic Rice (R)', price: 1100 },
    { id: 'cgr6', name: 'Chicken Garlic Rice (L)', price: 1400 },
    { id: 'cgr7', name: 'Prawns & Cuttlefish Garlic Rice (R)', price: 1200 },
    { id: 'cgr8', name: 'Prawns & Cuttlefish Garlic Rice (L)', price: 1850 },
  ],
  'Pasta': [
    { id: 'pa1', name: 'Creamy Vegetable Pasta (S)', price: 500 },
    { id: 'pa2', name: 'Creamy Vegetable Pasta (L)', price: 850 },
    { id: 'pa3', name: 'Creamy Chicken Pasta (S)', price: 900 },
    { id: 'pa4', name: 'Creamy Chicken Pasta (L)', price: 1400 },
    { id: 'pa5', name: 'Creamy Seafood Pasta (S)', price: 1200 },
    { id: 'pa6', name: 'Creamy Seafood Pasta (L)', price: 1750 },
    { id: 'pa7', name: 'Extra Cheese', price: 300 },
  ],
  'Spaghetti': [
    { id: 'sp1', name: 'Spaghetti Bolognese Beef (S)', price: 1400 },
    { id: 'sp2', name: 'Spaghetti Bolognese Beef (L)', price: 2000 },
    { id: 'sp3', name: 'Garlic Chicken Spaghetti (S)', price: 980 },
    { id: 'sp4', name: 'Garlic Chicken Spaghetti (L)', price: 1300 },
    { id: 'sp5', name: 'Garlic Seafood Spaghetti (S)', price: 1100 },
    { id: 'sp6', name: 'Garlic Seafood Spaghetti (L)', price: 1450 },
    { id: 'sp7', name: 'Garlic Beef Spaghetti (S)', price: 1550 },
    { id: 'sp8', name: 'Garlic Beef Spaghetti (L)', price: 2000 },
    { id: 'sp9', name: 'Creamy Chicken Spaghetti (S)', price: 1000 },
    { id: 'sp10', name: 'Creamy Chicken Spaghetti (L)', price: 1400 },
    { id: 'sp11', name: 'Creamy Seafood Spaghetti (S)', price: 1200 },
    { id: 'sp12', name: 'Creamy Seafood Spaghetti (L)', price: 1550 },
    { id: 'sp13', name: 'Creamy Beef Spaghetti (S)', price: 1600 },
    { id: 'sp14', name: 'Creamy Beef Spaghetti (L)', price: 2100 },
  ],
  'Noodles': [
    { id: 'nd1', name: 'Vegetable Noodles (S)', price: 450 },
    { id: 'nd2', name: 'Vegetable Noodles (L)', price: 600 },
    { id: 'nd3', name: 'Egg Noodles (S)', price: 600 },
    { id: 'nd4', name: 'Egg Noodles (L)', price: 900 },
    { id: 'nd5', name: 'Chicken Noodles (S)', price: 900 },
    { id: 'nd6', name: 'Chicken Noodles (L)', price: 1300 },
    { id: 'nd7', name: 'Seafood Noodles (S)', price: 1200 },
    { id: 'nd8', name: 'Seafood Noodles (L)', price: 1850 },
    { id: 'nd9', name: 'Mixed Noodles (S)', price: 1200 },
    { id: 'nd10', name: 'Mixed Noodles (L)', price: 1850 },
    { id: 'nd11', name: 'Special Mixed Noodles (S)', price: 1450 },
    { id: 'nd12', name: 'Special Mixed Noodles (L)', price: 2000 },
  ],
  'Chicken Bites': [
    { id: 'cb1', name: 'Fried Chicken (S)', price: 960 },
    { id: 'cb2', name: 'Fried Chicken (R)', price: 1540 },
    { id: 'cb3', name: 'Fried Chicken (L)', price: 3300 },
    { id: 'cb4', name: 'Butter Chicken (S)', price: 900 },
    { id: 'cb5', name: 'Butter Chicken (R)', price: 1400 },
    { id: 'cb6', name: 'Butter Chicken (L)', price: 3000 },
    { id: 'cb7', name: 'Pepper Chicken (S)', price: 1100 },
    { id: 'cb8', name: 'Pepper Chicken (R)', price: 1600 },
    { id: 'cb9', name: 'Pepper Chicken (L)', price: 3400 },
    { id: 'cb10', name: 'Devilled Chicken (S)', price: 850 },
    { id: 'cb11', name: 'Devilled Chicken (R)', price: 1400 },
    { id: 'cb12', name: 'Devilled Chicken (L)', price: 3000 },
    { id: 'cb13', name: 'Chicken Stew (S)', price: 700 },
    { id: 'cb14', name: 'Chicken Stew (R)', price: 1400 },
    { id: 'cb15', name: 'Chicken Stew (L)', price: 3000 },
    { id: 'cb16', name: 'Grilled Chicken (S)', price: 850 },
    { id: 'cb17', name: 'Grilled Chicken (R)', price: 1500 },
    { id: 'cb18', name: 'Grilled Chicken (L)', price: 3400 },
    { id: 'cb19', name: 'Chicken Kochchi Sambol (S)', price: 1000 },
    { id: 'cb20', name: 'Chicken Kochchi Sambol (R)', price: 1500 },
    { id: 'cb21', name: 'Chicken Kochchi Sambol (L)', price: 3400 },
    { id: 'cb22', name: 'Garlic Chicken (S)', price: 1180 },
    { id: 'cb23', name: 'Garlic Chicken (R)', price: 1600 },
    { id: 'cb24', name: 'Garlic Chicken (L)', price: 3400 },
    { id: 'cb25', name: 'Stir-Fried Wings (S)', price: 700 },
    { id: 'cb26', name: 'Stir-Fried Wings (R)', price: 1200 },
    { id: 'cb27', name: 'Stir-Fried Wings (L)', price: 2100 },
    { id: 'cb28', name: 'Luffa Chicken (S)', price: 700 },
    { id: 'cb29', name: 'Luffa Chicken (R)', price: 1400 },
    { id: 'cb30', name: 'Luffa Chicken (L)', price: 3000 },
  ],
  'Fish': [
    { id: 'fi1', name: 'Garoupa Fish (L)', price: 2400 },
    { id: 'fi2', name: 'Fish Fingers (S)', price: 960 },
    { id: 'fi3', name: 'Fish Fingers (R)', price: 1700 },
    { id: 'fi4', name: 'Fish Fingers (L)', price: 3600 },
    { id: 'fi5', name: 'Devilled Fish (S)', price: 1000 },
    { id: 'fi6', name: 'Devilled Fish (R)', price: 1950 },
    { id: 'fi7', name: 'Devilled Fish (L)', price: 3900 },
    { id: 'fi8', name: 'Oil Steamed Fish with Kochchi (S)', price: 1000 },
    { id: 'fi9', name: 'Oil Steamed Fish with Kochchi (R)', price: 1980 },
    { id: 'fi10', name: 'Oil Steamed Fish with Kochchi (L)', price: 3900 },
    { id: 'fi11', name: 'Fried Fish Tank (S)', price: 760 },
    { id: 'fi12', name: 'Fried Fish Tank (R)', price: 1330 },
    { id: 'fi13', name: 'Fried Fish Tank (L)', price: 2850 },
    { id: 'fi14', name: 'Small Fried Fish with Garlic (S)', price: 750 },
    { id: 'fi15', name: 'Small Fried Fish with Garlic (R)', price: 1300 },
    { id: 'fi16', name: 'Small Fried Fish with Garlic (L)', price: 2100 },
  ],
  'Seafood Bites': [
    { id: 'sb1', name: 'Mixed Devilled Seafood (S)', price: 1900 },
    { id: 'sb2', name: 'Mixed Devilled Seafood (R)', price: 2700 },
    { id: 'sb3', name: 'Mixed Devilled Seafood (L)', price: 3800 },
    { id: 'sb4', name: 'Mixed Grill Seafood (S)', price: 1400 },
    { id: 'sb5', name: 'Mixed Grill Seafood (R)', price: 2900 },
    { id: 'sb6', name: 'Mixed Grill Seafood (L)', price: 4400 },
    { id: 'sb7', name: 'Mixed Seafood Stew (S)', price: 1300 },
    { id: 'sb8', name: 'Mixed Seafood Stew (R)', price: 2000 },
    { id: 'sb9', name: 'Mixed Seafood Stew (L)', price: 3950 },
    { id: 'sb10', name: 'Devilled Prawns (S)', price: 1360 },
    { id: 'sb11', name: 'Devilled Prawns (R)', price: 2000 },
    { id: 'sb12', name: 'Devilled Prawns (L)', price: 4000 },
    { id: 'sb13', name: 'Batter Fried Prawns (S)', price: 1400 },
    { id: 'sb14', name: 'Batter Fried Prawns (R)', price: 2700 },
    { id: 'sb15', name: 'Batter Fried Prawns (L)', price: 4000 },
    { id: 'sb16', name: 'Devilled Cuttlefish (S)', price: 1200 },
    { id: 'sb17', name: 'Devilled Cuttlefish (R)', price: 2000 },
    { id: 'sb18', name: 'Devilled Cuttlefish (L)', price: 3950 },
    { id: 'sb19', name: 'Batter Fried Cuttlefish (S)', price: 1200 },
    { id: 'sb20', name: 'Batter Fried Cuttlefish (R)', price: 2000 },
    { id: 'sb21', name: 'Batter Fried Cuttlefish (L)', price: 4000 },
  ],
  'Vegetarian Bites': [
    { id: 'vb1', name: 'French Fries (S)', price: 900 },
    { id: 'vb2', name: 'French Fries (R)', price: 1400 },
    { id: 'vb3', name: 'French Fries (L)', price: 3000 },
    { id: 'vb4', name: 'Battered Mushrooms (S)', price: 600 },
    { id: 'vb5', name: 'Battered Mushrooms (R)', price: 1100 },
    { id: 'vb6', name: 'Battered Mushrooms (L)', price: 1700 },
    { id: 'vb7', name: 'Boiled Vegetables (S)', price: 600 },
    { id: 'vb8', name: 'Boiled Vegetables (R)', price: 900 },
    { id: 'vb9', name: 'Boiled Vegetables (L)', price: 1950 },
    { id: 'vb10', name: 'Green Salad (S)', price: 600 },
    { id: 'vb11', name: 'Green Salad (R)', price: 900 },
    { id: 'vb12', name: 'Potato Wedges (S)', price: 600 },
    { id: 'vb13', name: 'Potato Wedges (R)', price: 1200 },
    { id: 'vb14', name: 'Potato Wedges (L)', price: 2100 },
    { id: 'vb15', name: 'Fruit Plate (L)', price: 2500 },
    { id: 'vb16', name: 'Peanuts (S)', price: 250 },
    { id: 'vb17', name: 'Peanuts (R)', price: 450 },
    { id: 'vb18', name: 'Peanuts (L)', price: 850 },
    { id: 'vb19', name: 'Cashews (S)', price: 1400 },
    { id: 'vb20', name: 'Cashews (R)', price: 2800 },
    { id: 'vb21', name: 'Cashews (L)', price: 4000 },
    { id: 'vb22', name: 'Mixers (S)', price: 220 },
    { id: 'vb23', name: 'Mixers (R)', price: 440 },
    { id: 'vb24', name: 'Mixers (L)', price: 660 },
    { id: 'vb25', name: 'Cheese & Grapes', price: 600 },
    { id: 'vb26', name: 'Onion Rings', price: 400 },
  ],
  'Sausages': [
    { id: 'ss1', name: 'Fried Sausage (S)', price: 800 },
    { id: 'ss2', name: 'Fried Sausage (R)', price: 1400 },
    { id: 'ss3', name: 'Fried Sausage (L)', price: 3200 },
    { id: 'ss4', name: 'Grilled Sausage (S)', price: 1100 },
    { id: 'ss5', name: 'Grilled Sausage (R)', price: 1500 },
    { id: 'ss6', name: 'Grilled Sausage (L)', price: 3500 },
    { id: 'ss7', name: 'Sausage Stew (S)', price: 1000 },
    { id: 'ss8', name: 'Sausage Stew (R)', price: 1500 },
    { id: 'ss9', name: 'Sausage Stew (L)', price: 3500 },
    { id: 'ss10', name: 'Devilled Sausage (S)', price: 900 },
    { id: 'ss11', name: 'Devilled Sausage (R)', price: 1500 },
    { id: 'ss12', name: 'Devilled Sausage (L)', price: 3400 },
  ],
  'Beef': [
    { id: 'bf1', name: 'Beef Curry (R)', price: 1900 },
    { id: 'bf2', name: 'Beef Curry (L)', price: 3900 },
    { id: 'bf3', name: 'Devilled Beef (R)', price: 1800 },
    { id: 'bf4', name: 'Devilled Beef (L)', price: 3800 },
    { id: 'bf5', name: 'Fried Beef (R)', price: 2000 },
    { id: 'bf6', name: 'Fried Beef (L)', price: 4100 },
    { id: 'bf7', name: 'Beef Stew (R)', price: 1800 },
    { id: 'bf8', name: 'Beef Stew (L)', price: 3800 },
    { id: 'bf9', name: 'Pepper Beef (R)', price: 1900 },
    { id: 'bf10', name: 'Pepper Beef (L)', price: 3900 },
  ],
  'Pork': [
    { id: 'pk1', name: 'Pork Curry (R)', price: 1780 },
    { id: 'pk2', name: 'Pork Curry (L)', price: 3700 },
    { id: 'pk3', name: 'Devilled Pork (R)', price: 1700 },
    { id: 'pk4', name: 'Devilled Pork (L)', price: 3600 },
    { id: 'pk5', name: 'Stir-Fried Pork (R)', price: 1780 },
    { id: 'pk6', name: 'Stir-Fried Pork (L)', price: 3700 },
    { id: 'pk7', name: 'Pork Stew (R)', price: 1890 },
    { id: 'pk8', name: 'Pork Stew (L)', price: 4100 },
    { id: 'pk9', name: 'Pepper Pork (R)', price: 1950 },
    { id: 'pk10', name: 'Pepper Pork (L)', price: 4200 },
  ],
  'Mutton': [
    { id: 'mt1', name: 'Mutton Curry (R)', price: 2380 },
    { id: 'mt2', name: 'Mutton Curry (L)', price: 4760 },
    { id: 'mt3', name: 'Mutton Stew (R)', price: 2450 },
    { id: 'mt4', name: 'Mutton Stew (L)', price: 4860 },
    { id: 'mt5', name: 'Pepper Mutton (R)', price: 2450 },
    { id: 'mt6', name: 'Pepper Mutton (L)', price: 4860 },
  ],
  'Extra Curry': [
    { id: 'ec1', name: 'Chicken Curry 400g', price: 1500 },
    { id: 'ec2', name: 'Chicken Curry 800g', price: 3000 },
    { id: 'ec3', name: 'Beef Curry 400g', price: 1960 },
    { id: 'ec4', name: 'Beef Curry 800g', price: 3900 },
    { id: 'ec5', name: 'Pork Curry 400g', price: 1980 },
    { id: 'ec6', name: 'Pork Curry 800g', price: 3920 },
    { id: 'ec7', name: 'Mutton Curry 400g', price: 2250 },
    { id: 'ec8', name: 'Mutton Curry 800g', price: 4400 },
    { id: 'ec9', name: 'Thalapath Fish 400g', price: 1950 },
    { id: 'ec10', name: 'Thalapath Fish 800g', price: 3900 },
    { id: 'ec11', name: 'Prawns Curry 400g', price: 1950 },
    { id: 'ec12', name: 'Prawns Curry 800g', price: 3900 },
    { id: 'ec13', name: 'Crab Curry 400g', price: 1850 },
    { id: 'ec14', name: 'Crab Curry 800g', price: 3600 },
    { id: 'ec15', name: 'Egg Curry 400g', price: 1420 },
    { id: 'ec16', name: 'Egg Curry 800g', price: 2350 },
  ],
  'Eggs & Omelettes': [
    { id: 'eg1', name: 'Boiled Egg', price: 150 },
    { id: 'eg2', name: "Bull's Eye Egg", price: 150 },
    { id: 'eg3', name: 'Sri Lankan Omelette (3 Eggs)', price: 550 },
    { id: 'eg4', name: 'Sausage Omelette', price: 650 },
    { id: 'eg5', name: 'Cheese Chicken Omelette', price: 1000 },
    { id: 'eg6', name: 'Cheese Omelette', price: 800 },
    { id: 'eg7', name: 'Poached Egg', price: 200 },
  ],
  'Satay Sticks': [
    { id: 'st1', name: 'Vegetable Satay', price: 300 },
    { id: 'st2', name: 'Chicken Satay', price: 450 },
    { id: 'st3', name: 'Seafood Satay', price: 650 },
    { id: 'st4', name: 'Beef Satay', price: 750 },
  ],
  'Desserts': [
    { id: 'ds1', name: 'Watalappam', price: 250 },
    { id: 'ds2', name: 'Caramel Pudding', price: 200 },
    { id: 'ds3', name: 'Vanilla Ice Cream', price: 300 },
    { id: 'ds4', name: 'Vanilla Ice Cream with Trekle', price: 380 },
    { id: 'ds5', name: 'Vanilla Ice Cream with Topping', price: 380 },
    { id: 'ds6', name: 'Chocolate Ice Cream', price: 350 },
  ],
  'Cold Beverages': [
    { id: 'cv1', name: 'Watermelon Juice', price: 380 },
    { id: 'cv2', name: 'Papaya Juice', price: 380 },
    { id: 'cv3', name: 'Wood Apple Juice', price: 380 },
    { id: 'cv4', name: 'Lemon Juice', price: 200 },
    { id: 'cv5', name: 'Piña Colada', price: 550 },
    { id: 'cv6', name: 'Kekiri Milkshake', price: 400 },
    { id: 'cv7', name: 'Chocolate Milkshake', price: 400 },
    { id: 'cv8', name: 'Mango Lassi', price: 500 },
    { id: 'cv9', name: 'Avocado Lassi', price: 500 },
  ],
  'Hot Beverages': [
    { id: 'hv1', name: 'Plain Tea', price: 80 },
    { id: 'hv2', name: 'Black Coffee', price: 120 },
    { id: 'hv3', name: 'Milk Tea', price: 180 },
    { id: 'hv4', name: 'Milk Coffee', price: 200 },
    { id: 'hv5', name: 'Masala Tea', price: 250 },
  ],
};